version: "3.8"
services:
  redis:
    image: "redis:latest"
    container_name: app_redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql/mysql-server:5.7
    container_name: app_mysql
    ports:
      - 3306:3306
    volumes:
      - "./db:/var/lib/mysql"
      - "./conf/my.cnf:/etc/my.cnf"
      - "./init:/docker-entrypoint-initdb.d/"
    environment:
      MYSQL_ROOT_PASSWORD: 121891

  app:
    restart: always
    build: .
    working_dir: /eblog
    volumes:
      - ./eblog:/opt/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
      command: mvn clean spring-boot:run
      depends_on:
        - mysql
        - redis