server:
  port: 8888
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用SQL分析的时候
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://47.108.237.10:3306/eblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  freemarker:
    settings:
      classic_compatible: true #处理空值
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
  servlet:
    multipart:
      max-file-size: 10000000
      max-request-size: 20000000
  redis:
    host: 47.108.237.10
    port: 6379
  data:
    elasticsearch:
      cluster-name: es
      cluster-nodes: 47.108.237.10:9200
      repositories:
        enabled: true
  rabbitmq:
    host: 47.108.237.10
    port: 5672
    username: root
    password: 121891
    virtual-host: eblog


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.lmy.eblog: DEBUG
    com.lmy.eblog.mapper: DEBUG

yun:
  endpoint: https://oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAI4GDZpCFa7NtQY5RC7Qw3
  accessKeySecret: bauRCDzYWcgvDvs0icLQLEhcHxV9TW
  bucketName: ferryblog

im:
  server:
    port: 9326