server:
  port: 8080
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用SQL分析的时候
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/eblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 121891
  freemarker:
    settings:
      classic_compatible: true #处理空值
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
  redis:
    host: 192.168.75.139
    port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml